version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=powerwall
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d powerwall"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - timescale-data:/var/lib/postgresql/data
    networks:
      - pwserver-network

  pwserver:
    build:
      context: ./PWServer
      dockerfile: Dockerfile
      target: build
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Timescale=Host=timescaledb;Port=5432;Database=powerwall;Username=postgres;Password=postgres;Pooling=true;Maximum Pool Size=50;Timezone=UTC
    volumes:
      - ./PWServer:/src
    depends_on:
      timescaledb:
        condition: service_healthy
    networks:
      - pwserver-network
    command: ["dotnet", "watch", "run", "--project", "/src/PWServer.csproj", "--urls", "http://+:8080"]

volumes:
  timescale-data:

networks:
  pwserver-network:
    driver: bridge